login/urls.py
from django.conf.urls import include , url
from . import views
from django.contrib.auth.views import login


app_name = 'login'
urlpatterns = [
    url(r'^$' , login  , {'template_name':'login/login.html'},name="login"),
    url(r'^profile/$' , views.home , name="home"),
]

music/urls.py
from django.conf.urls import include , url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view() , name="detail"),
    url(r'^service.html/$' , views.service , name="service"),
    url(r'^disclaimer.html/$' , views.disclaimer , name = "disclaimer"),
    ]

new/urls.py
from django.conf.urls import include , url
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include("music.urls",namespace="music"),name="music"),
    url(r'^contact/', include("contact.urls",namespace="contact"),name="contact"),
    url(r'^polls/', include('polls.urls',namespace="polls"), name='polls'),
    url(r'^signup/',include("signup.urls",namespace="signup"), name='signup'),
    url(r'^account/$',include("account.urls",namespace="account"),name="account"),
    url(r'^login/',include('login.urls',namespace="login"),name='login'),
    url(r'^logout/',include('logout.urls',namespace="logout"),name='logout'),
]



#	url(r'^accounts/register/$',
# CreateView.as_view(template_name='Election_Portal/register.html',
# form_class=UserCreationForm,success_url='/editprofile'),name='register'),

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    year_of_release = models.CharField(max_length=50)
    image = models.CharField(max_length=1000)


    def __str__(self):
        return f'{self.artist}--{self.genre}--{self.year_of_release}--{self.image}'


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=100)
    is_favourite = models.BooleanField(default=False)



    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from .models import Album
from django.http import HttpResponse
from django.template import loader


class IndexView(generic.ListView):

    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()



class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

def service(request):

    t=loader.get_template('music/service.html')
    return HttpResponse(t.render({},request))

def disclaimer(request):
    t=loader.get_template('music/disclaimer.html')
    return HttpResponse(t.render({},request))

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title  %}
            BANK HOME PAGE
        {% endblock %}
    </title>
    {% include 'music/head.html' %}

</head>
<body>

{% include 'music/navbar.html' %}

<br> <br>
<h1 style="font-family : 'Bitstream Vera Sans' ; text-align: center ; color : navy ;"   >WITH YOU , RIGHT THROUGH</h1>
<br>
<br>



{% include 'music/corousel.html' %}



{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/corousel.html
<div class="container">

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="https://i.imgur.com/TRw3Q0V.jpg"
             style="width:100%; height: 400px">
      </div>

      <div class="item">
        <img src="https://i.imgur.com/gwOVGzi.jpg"
             style="width:100%; height: 400px">
      </div>

      <div class="item">
        <img src="https://www.buybitcoinworldwide.com/img/goodicons/cash.png"
             style="width:100%; height: 400px">
      </div>
        <div class="item">
        <img src="https://i.imgur.com/zFWAEAc.jpg"
             style="width:100%; height: 400px">
      </div>
        <div class="item">
        <img src="https://i.imgur.com/r940Ss5.jpg"
             style="width:100%; height: 400px">
      </div>
         <div class="item">
        <img src="https://i.imgur.com/WDJejVB.jpg"
             style="width:100%; height: 400px">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %}Album Details {% endblock %}
{% block body %}




<h1>{{ "ALBUM ARTIST ->  " }}{{ album.artist }}</h1>
<h3>{{ "ALBUM GENRE  ->  "  }}{{ album.genre }}</h3>


<img src="{{ album.image }}" alt = "{{ album.year_of_release }}" width="100px"
            height ="100px" >
    <br>

{% if error_message %}
    <p> <strong>{{ error_message }}</strong></p>

{% endif %}

    {% for song in album.song_set.all %}
        <p style="font-size: 50px ; color: orange">  {{ song.song_title }}</p>
        <br>
      {% endfor %}


{% endblock %}

music/templates/music/disclaimer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title  %}
            SERVICES
        {% endblock %}
    </title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>

{% include 'music/navbar.html' %}

<br>
<br>
<br>
<br>
<br>
<h3 style="color: #5a40cc ; text-align: center ; font-size: 30px">Disclaimer</h3>
<p style="font-size: 25px ; color: midnightblue;">
    The information, material, advices, suggestions, illustration, notification,
    circulars etc. are collectively stated “the content” in this website. If the
    said contents contains any mistakes, omissions,inaccuracies and typographical
    errors, etc. A4 BANK assumes no responsibility thereof. A4 BANK
    makes no warranties or representation regarding any content provided through
    this website and disclaims its liabilities in respect thereof. A4 BANK
    has taken all steps to prevent the introduction of viruses, worms or other
    destructive material to this website. However, A4 BANK does not guarantee
    or warrant that this website or the material that may be downloaded from this
    website does not contain any such destructive material Any action on your part
    on the basis of said contents is entirely at your risk and responsibility.
    A4 BANK reserves its right to correct any part of the said content at
    any time as and when required at its sole discretion. The contents of this website
    shall not be displayed or printed in any form in part or whole without the prior
    written approval of A4 BANK.<br><br>
An entity wanting to create a link to the A4 BANKs' website is required to
    obtain prior written approval from A4 BANK before doing so. A4 BANK may, at its absolute discretion, give or refuse to give such approval and
    may as well rescind any approval granted and require the removal of any link
    to A4 BANK website at any time. Any link to bank's website must be directed
    to the homepage of Bank's corporate website only and 'framing' or 'deep-linking'
    of bank's website or content is strictly prohibited. Any person using such
    unauthorised link, website will be doing so at his own risk and responsibility
    and A4 BANK will not be liable in any manner for any loss or damage
    caused to the user or any party.<br><br>
Any use or display of A4 BANK logo, trade name, trademark, web content
    or material in any form is not permitted except with the prior written approval
    from A4 BANK.<br><br>
A4 BANK will not be responsible for the action of other websites and that
    the Banks' name is protected by trademark and other relevant legislations.
    The Bank reserves the rights to prosecute and take legal action of both civil
    and criminal against people / persons and / or entities who may be acting in
    any way purportedly on behalf of the Bank without its express permission and authorisation.<br>


</p>
<br><br>
<p style="font-family: cursive ; color : darkblue ; font-size: 50px ; padding-left: 50px ; text-align: center" >
    <a  href="{% url 'music:index' %}">
        <button style=" width: 300px ; height: 45px" class="btn btn-success btn-lg">Home</button>
    </a>


</p>


</body>

music/templates/music/head.html
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" >
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

music/templates/music/index.html
{% extends 'music/base.html' %}



{% block body %}

<br>
    <br>
<p style="font-family: cursive ;color: #0c5460 ; font-size: 50px ; text-align: center">
Thanks for choosing Us.<br>
We are happy that you gave us the opportunity to help you.<br>
You Nurture LIFE , We Nurture Your Dreams .
</p>
<br><br><br>
<p style="font-family: cursive ; color : darkblue ; font-size: 50px ; padding-left: 50px ;" >
    <a href="service.html">
        <button style="margin-right: 550px ; width: 300px ; height: 45px" class="btn btn-success btn-lg">Services Available</button>
    </a>
    <a href="disclaimer.html">
        <button style=" width: 300px ; height: 45px" class="btn btn-success btn-lg">Disclaimer</button>
    </a>

</p>




{% endblock %}

music/templates/music/navbar.html
<!-- THIS IS OUR NAV BAR -->

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header" style="width: 100px;">
      <a class="navbar-brand"  style="font-size: 1.5em; font-weight: bold; " href="{% url 'music:index' %}">A4 Bank</a>
    </div>
    <ul class="nav navbar-nav">
      <li style="font-size: 1.2em;"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-home"></span>  Home</a></li>
      {% if user.is_authenticated %}
        <li class="dropdown" style="font-size: 1.2em;">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-folder-open"></span> Profile
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">View Profile</a></li>
          <li><a href="#">Transfer Funds</a></li>
        </ul>
      </li>
      {% endif %}
      <li><a href="#" style="font-size: 1.2em;"><span class="glyphicon glyphicon glyphicon-tasks"></span> Products and Services</a></li>
      <li><a href="{% url 'contact:index' %}" style="font-size: 1.2em;"><span class="glyphicon glyphicon-phone-alt"></span> Contact Us</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if not user.is_authenticated %}
      <li style="font-size: 1.2em;"><a href="{% url 'signup:home' %}"><span class="glyphicon glyphicon-user"></span> Register</a>
      </li>
    {% endif %}
      <li style="font-size: 1.2em;">
           {% if user.is_authenticated %}
               <a href="{% url 'logout:logout' %}"> Logout</a>
           {% else %}
                <a href="{% url 'login:login' %}"> Login</a>
           {% endif %}
          </li>
    </ul>
  </div>
</nav>

music/templates/music/service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title  %}
            SERVICES
        {% endblock %}
    </title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>

{% include 'music/navbar.html' %}

<br>
<br>
<br>
<br>
<br>

    <ul type="disc" style="font-size: 50px ; padding-left: 100px ; color: #0c5460">
        <li>Checking accounts.</li>
        <li>Savings accounts.</li>
        <li>Debit and credit cards.</li>
        <li>Merchant services.</li>
        <li>Cash management.</li>
        <li>Money Transfer.</li>
</ul>

<p style="font-family: cursive ; color : darkblue ; font-size: 50px ; padding-left: 50px ;text-align: center"  >
    <a  href="{% url 'music:index' %}">
        <button style=" width: 300px ; height: 45px" class="btn btn-success btn-lg">Home</button>
    </a>


</p>


</body>