contact/urls.py
from django.conf.urls import include , url
from . import views
app_name = 'contact'


urlpatterns = [

    url(r'^$' ,views.index , name="index"),

    url(r'^write/$', views.write, name='write'),


]

login/urls.py
from django.conf.urls import include , url
from . import views
from django.contrib.auth.views import login


app_name = 'login'
urlpatterns = [
    url(r'^$' , login  , {'template_name':'login/login.html'},name="login"),
    url(r'^profile/$' , views.home , name="home"),
]

new/urls.py
from django.conf.urls import include , url
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include("music.urls",namespace="music"),name="music"),
    url(r'^contact/', include("contact.urls",namespace="contact"),name="contact"),
    url(r'^polls/', include('polls.urls',namespace="polls"), name='polls'),
    url(r'^signup/',include("signup.urls",namespace="signup"), name='signup'),
    url(r'^account/$',include("account.urls",namespace="account"),name="account"),
    url(r'^login/',include('login.urls',namespace="login"),name='login'),
    url(r'^logout/',include('logout.urls',namespace="logout"),name='logout'),
]



#	url(r'^accounts/register/$',
# CreateView.as_view(template_name='Election_Portal/register.html',
# form_class=UserCreationForm,success_url='/editprofile'),name='register'),

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms
import django.contrib.auth.forms
from django.contrib.auth.models import User


class WriteToUs(forms.Form):
    Subject = forms.CharField(max_length=30, required=True, help_text='What is it related to?' )
    Message = forms.CharField(max_length=1000, required=True, help_text='What do you want to say?',widget=forms.Textarea)

contact/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.template import Context
from django.template.loader import render_to_string, get_template
from django.core.mail import send_mail
from django.conf import settings
from . import forms
from django.template import loader


def index(request):
    t=loader.get_template('contact/index.html')
    return HttpResponse(t.render({},request))


def write(request):
    to_list = ['avi.chawlaavi@gmail.com']
    from_email = settings.EMAIL_HOST_USER


    if request.method == 'POST':
        form = forms.WriteToUs(request.POST)
        if form.is_valid():

            subject = form.cleaned_data.get('Subject')
            message = form.cleaned_data.get('Message')
            send_mail(subject, message, recipient_list=to_list, from_email=from_email,fail_silently=True)
            t = loader.get_template('contact/thanks.html')
            return HttpResponse(t.render({},request))
    else:
        form = forms.WriteToUs()
    return render(request, 'contact/write.html', {'form': form})

contact/templates/contact/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title  %}
            Contact
        {% endblock %}
    </title>
    {% load staticfiles %}
    {% include 'contact/head.html' %}

</head>
<body>



<br> <br>
<h1 style="font-family : 'Bitstream Vera Sans' ; text-align: center ; color : navy ;"   >WITH YOU , RIGHT THROUGH</h1>
<br>
<br>

{% include 'contact/navbar.html' %}



{% block body %}
{% endblock %}
</body>
</html>

contact/templates/contact/head.html
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" >
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

contact/templates/contact/index.html
{% extends 'contact/base.html' %}

{% block body %}

<br>
    <br>
<p style="font-family: cursive ;color: #0c5460 ; font-size: 100px ; text-align: center">
WELCOME<br>


</p>

<br><br><br>
<p style="font-family: cursive ;color: #0c5460 ; font-size: 50px ; text-align: center">
In case you are facing any issues with our service or you want to give any suggestions<br>
    THEN<br>

    You can either visit your nearest branch <br>
    OR<br>
    Contact us on our toll free number:1800 180 9999<br>
    The toll free helpline is available 24*7 for you in 10 languages.<br><br>
    If you want to connect to your branch then you can choose the appropriate option and then <br>
    Type in your branch code.This will connect you to your branch.<br>
    NOTE: This service also depends upon the Branch Timings.

<br>
<p style="font-family: cursive ; color : darkblue ; font-size: 30px ; padding-left: 50px ;text-align: center"  >
    <a  href="{% url 'contact:write' %}">
        <button style=" margin-right: 70px; width: 300px ; height: 45px" class="btn btn-success btn-lg">Write To Us</button>
    </a>


</p>


</p>



{% endblock %}

contact/templates/contact/navbar.html
<!-- THIS IS OUR NAV BAR -->

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header" style="width: 100px;">
      <a class="navbar-brand"  style="font-size: 1.5em; font-weight: bold; " href="{% url 'music:index' %}">A4 Bank</a>
    </div>
    <ul class="nav navbar-nav">
      <li style="font-size: 1.2em;"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-home"></span>  Home</a></li>
      {% if user.is_authenticated %}
        <li class="dropdown" style="font-size: 1.2em;">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-folder-open"></span> Profile
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">View Profile</a></li>
          <li><a href="#">Transfer Funds</a></li>
        </ul>
      </li>
      {% endif %}
      <li><a href="#" style="font-size: 1.2em;"><span class="glyphicon glyphicon glyphicon-tasks"></span> Products and Services</a></li>
      <li><a href="{% url 'contact:index' %}" style="font-size: 1.2em;"><span class="glyphicon glyphicon-phone-alt"></span> Contact Us</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if not user.is_authenticated %}
      <li style="font-size: 1.2em;"><a href="{% url 'signup:home' %}"><span class="glyphicon glyphicon-user"></span> Register</a>
      </li>
    {% endif %}
      <li style="font-size: 1.2em;">
           {% if user.is_authenticated %}
               <a href="{% url 'logout:logout' %}"> Logout</a>
           {% else %}
                <a href="{% url 'login:login' %}"> Login</a>
           {% endif %}
          </li>
    </ul>
  </div>
</nav>

contact/templates/contact/thanks.html
{% extends 'contact/base.html' %}


{% block body %}
    <br><br><br><br><br><br><br><br>

    <h1 style="text-align: center ; color: #5a40cc">YOUR MESSAGE HAS BEEN SENT.</h1>
    <h1 style="text-align: center ; color: #5a40cc">WE WILL GET BACK TO YOU WITHIN 24 HRS.</h1>



{% endblock %}

contact/templates/contact/write.html
{% extends 'contact/base.html' %}

{% block body %}
    {% if user.is_authenticated %}
      <h2 style="text-align:center; color:blue;">Write To Us</h2>
        <br><br><br>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <p style="margin-left: 500px">
            {{ field.label_tag }}
          <br>
            {{ field }}

           {% if field.help_text %}
              <small style="color: blueviolet">{{ field.help_text }}</small>
            {% endif %}
            <br><br><br>
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <button style=" margin-left: 625px; width: 100px ; height: 45px" class="btn btn-success btn-lg">Send</button>
      </form>
    {% else %}
        <br><br><br><br><br><br><br><br>
        <div class="alert alert-success" style="width: 400px ; text-align: center ; margin-left: 430px ; left: 50%">
            <center>
                <strong style="text-align: center">
                 LOGIN FIRST TO USE THIS.</strong>
            </center>
        </div>

        <a href = "{% url 'login:login' %}">
            <button style=" margin-left: 575px;
                width: 100px ; height: 45px"
                    class="btn btn-success btn-lg">Login
            </button>
        </a>
    {% endif %}

{% endblock %}