login/urls.py
from django.conf.urls import include , url
from . import views
from django.contrib.auth.views import login


app_name = 'login'
urlpatterns = [
    url(r'^$' , login  , {'template_name':'login/login.html'},name="login"),
    url(r'^profile/$' , views.home , name="home"),
]

music/urls.py
from django.conf.urls import include , url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view() , name="detail"),
    url(r'^service.html/$' , views.service , name="service"),
    url(r'^disclaimer.html/$' , views.disclaimer , name = "disclaimer"),
    ]

new/urls.py
from django.conf.urls import include , url
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include("music.urls",namespace="music"),name="music"),
    url(r'^contact/', include("contact.urls",namespace="contact"),name="contact"),
    url(r'^polls/', include('polls.urls',namespace="polls"), name='polls'),
    url(r'^signup/',include("signup.urls",namespace="signup"), name='signup'),
    url(r'^account/$',include("account.urls",namespace="account"),name="account"),
    url(r'^login/',include('login.urls',namespace="login"),name='login'),
    url(r'^logout/',include('logout.urls',namespace="logout"),name='logout'),
]



#	url(r'^accounts/register/$',
# CreateView.as_view(template_name='Election_Portal/register.html',
# form_class=UserCreationForm,success_url='/editprofile'),name='register'),

signup/urls.py
from django.contrib.auth import views as auth_views

from django.conf.urls import include , url
from . import views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

app_name = 'signup'

urlpatterns=[
    url(r'^$',CreateView.as_view(template_name='signup/signup.html',
             form_class=UserCreationForm,success_url='firsttime'), name="home"),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^firsttime/$',views.edit_profile,name='editprofile'),
    #url(r'^successsignup/$' , views.success , name="success")
]

login/models.py
from django.db import models

# Create your models here.

signup/models.py
from __future__ import unicode_literals

from django.db import models
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User,Permission
from django.core.validators import MaxValueValidator


class Profile(models.Model):
	userid=User(models.ForeignKey(User))
	first_name=models.CharField(max_length=100,default='Please enter your ')
	last_name=models.CharField(max_length=100,default='Profile')
	birthdate=models.DateField('Date of Birth',default=timezone.now)
	emailid=models.EmailField()
	account_balance = models.IntegerField(default=0)
	account_number = models.IntegerField(default=0)

	def __str__(self):
		return f"{self.first_name} {self.last_name}"

login/forms.py
from django import forms
import django.contrib.auth.forms
from django.contrib.auth.models import User


class Loginform(forms.Form):
    Username = forms.CharField(max_length=30, required=True, help_text='Your Login ID.')
    Password = forms.CharField(max_length=50, required=True, help_text='Your Password.')

signup/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

# class SignUpForm(UserCreationForm):
#     first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
#     last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
#     email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
#     mobile = forms.CharField(max_length=10, required=True, help_text='Required.')
#
#     class Meta:
#         model = User
#         fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'mobile')

class EditProfileForm(forms.ModelForm):
	class Meta(object):
		model = Profile
		fields = ['first_name','last_name','birthdate','emailid']

login/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.template.loader import render_to_string, get_template
from django.http import HttpResponse
from .forms import Loginform
from django.contrib.auth.views import login


def home(request):
    t = get_template('login/loginsuccess.html')
    return HttpResponse(t.render({}, request))

signup/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.template import loader
from django.template.loader import render_to_string, get_template
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
import datetime
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.db import transaction
from django.core.mail import EmailMessage,send_mail
from .forms import EditProfileForm
from django.contrib.auth.models import User
from django import forms
from random import randint


def home(request):
    return render(request, 'signup/signup.html')


def edit_profile(request):
    uid = request.user
    fl=False
    try:
        fl=True
        profile = Profile.objects.get(userid=uid)
        data={
        'first_name':profile.first_name,
        'last_name':profile.last_name,
        'birthdate':profile.birthdate,
        'emailid':profile.emailid,
        'account_number':profile.account_number,
        'account_balance':profile.account_balance,
        }
    except:
        data={
        'first_name':'',
        'last_name':'',
        }
    form = EditProfileForm(request.POST or None,initial=data)
    if form.is_valid():
        p = form.save(commit=False)
        p.userid = request.user
        p.account_number= randint(10**8 , 10 **12)
        p.save()
        t = loader.get_template('signup/successsignup.html')
        return HttpResponse(t.render({}, request))
    context = {
        "form": form,
    }
    return render(request, 'signup/firstlogin.html', context)




# def signup(request):
#     if request.method == 'POST':
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             t = get_template('signup/successsignup.html')
#             return HttpResponse(t.render({}, request))
#     else:
#         form = SignUpForm()
#     return render(request, 'signup/signup.html', {'form': form})

signup/templates/signup/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Money Flow</title>
    <style>

    </style>
      {% include 'signup/head.html' %}

  </head>
  <body>
  {% include 'signup/navbar.html' %}

    <br><br><br><br>

    <h1 style="font-family : 'Bitstream Vera Sans' ; text-align: center ; color : navy ;"   >WITH YOU , RIGHT THROUGH</h1>

    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

signup/templates/signup/firstlogin.html
{% extends 'signup/base.html' %}

{% block content %}
    <div class="container">
        <div class="page-header">
            <h1 style="text-align:center; color:blue;">Enter Your Personal Info.</h1>
        </div>
        <center>
            <div class="jumbotron">
                <form method="post">
                    {% csrf_token %}
                         <!-- {{ form.as_p }} -->

                    {% for field in form %}
                        <p>
                            {{ field.label_tag }}<br>
                            {{ field }}<br>
                                {% if field.help_text %}
                                    <div style="color: grey;font-size: 15px">{{ field.help_text }}</div>
                                 {% endif %}
                             {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                             {% endfor %}
                        </p>
                    {% endfor %}
                    <br><br>
                    <a href="{% url 'music:index' %}">
                        <button class="btn btn-success btn-lg"
                            type="submit" style="text-align: center">Sign up</button>

                    </a>

                </form>
            </div>
        </center>
    </div>
{% endblock %}

signup/templates/signup/head.html
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'signup/style.css' %}" >
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

signup/templates/signup/home.html
{% extends 'signup/base.html' %}


{% block content %}

{% if user.is_authenticated %}
  <h2 style="text-align:center; color:green;">Welcome, {{ user.get_full_name }}</h2>
  <p style="text-align:center;" >Your account balance is <span style="color:red;">1030400.50</span></p>

{% else %}
HOME PAGE CONTENT

{% endif %}

{% endblock %}

signup/templates/signup/login.html
{% extends 'signup/base.html' %}

{% block content %}
  <h2 style="color:blue; font-size:40px;">Log in</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
         {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'signup:signup' %}">New to My Site? Sign up</a>
  </form>
{% endblock %}

signup/templates/signup/navbar.html
<!-- THIS IS OUR NAV BAR -->

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header" style="width: 100px;">
      <a class="navbar-brand"  style="font-size: 1.5em; font-weight: bold; " href="{% url 'music:index' %}">A4 Bank</a>
    </div>
    <ul class="nav navbar-nav">
      <li style="font-size: 1.2em;"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-home"></span>  Home</a></li>
      {% if user.is_authenticated %}
        <li class="dropdown" style="font-size: 1.2em;">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-folder-open"></span> Profile
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">View Profile</a></li>
          <li><a href="#">Transfer Funds</a></li>
        </ul>
      </li>
      {% endif %}
      <li><a href="#" style="font-size: 1.2em;"><span class="glyphicon glyphicon glyphicon-tasks"></span> Products and Services</a></li>
      <li><a href="{% url 'contact:index' %}" style="font-size: 1.2em;"><span class="glyphicon glyphicon-phone-alt"></span> Contact Us</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if not user.is_authenticated %}
      <li style="font-size: 1.2em;"><a href="{% url 'signup:home' %}"><span class="glyphicon glyphicon-user"></span> Register</a>
      </li>
    {% endif %}
      <li style="font-size: 1.2em;">
           {% if user.is_authenticated %}
               <a href="{% url 'logout:logout' %}"> Logout</a>
           {% else %}
                <a href="{% url 'login:login' %}"> Login</a>
           {% endif %}
          </li>
    </ul>
  </div>
</nav>

signup/templates/signup/signup.html
{% extends 'signup/base.html' %}

{% block content %}
    <div class="container">
        <div class="page-header">
            <h1 style="text-align:center; color:blue;">Sign up</h1>
        </div>
        <center>
            <div class="jumbotron">
                <form method="post">
                    {% csrf_token %}
                         <!-- {{ form.as_p }} -->

                    {% for field in form %}
                        <p>
                            {{ field.label_tag }}<br>
                            {{ field }}<br>
                                {% if field.help_text %}
                                    <div style="color: grey;font-size: 15px">{{ field.help_text }}</div>
                                 {% endif %}
                             {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                             {% endfor %}
                        </p>
                    {% endfor %}
                    <br><br>
                    <a href="signup.html/successsignup.html">
                        <button class="btn btn-success btn-lg"
                            type="submit" style="text-align: center">Sign up</button>

                    </a>

                </form>
            </div>
        </center>
    </div>
{% endblock %}

signup/templates/signup/successsignup.html
{% extends 'signup/base.html' %}



{% block content %}
    <br><br><br><br><br><br><br><br>
    <div class="alert alert-success" style="width: 400px ; text-align: center ; margin-left: 430px ; left: 50%">
        <center>
            <strong style="text-align: center">Success!
             SIGNUP SUCCESSFUL.</strong>
        </center>
    </div>


    <br>
    <a href="{% url 'login:login' %}">
    <p style="text-align: center">
        <button class="btn btn-success btn-lg"
                            type="submit" style="text-align: center">Login</button>
    </p>
    </a>

{% endblock %}